### ISSUE TITLE
Add MIT license?

### ISSUE THREAD

**Issue by xet7** [chr15m/motionless#1]
Hi,
could you add MIT license? Without it, it's still propietary, and I'm not allowed to modify it, distribute etc.

About [common good](https://github.com/chr15m), I have maintained [Wekan](https://wekan.github.io) with [MIT license](https://github.com/wekan/wekan/blob/master/LICENSE) for 4 years, since [2016-12-16](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v0110-2016-12-16-wekan-fork-first-release).

In [TSC platform game project](https://secretchronicles.org) I built website in English and Finnish, and binary packages for many operating systems. Others did most of game related code. I'm currently looking for alternatives to [TSC website that uses nanoc static website compiler](https://github.com/Secretchronicles/main-website). Ruby-based nanoc sometimes has updates that cause static website building be broken, requiring some changes.

I came here because I noticed [your HN post](https://news.ycombinator.com/item?id=25396806).

**Comment by chr15m** [comment]
Done! Thanks for the suggestion.
