### ISSUE TITLE
Examples directory?

### ISSUE THREAD

**Issue by xet7** [chr15m/motionless#2]
Hi,
it seems you have examples at readme.

Could you move those examples to new `examples` directory, where would subdirectories named by example name?

For example, subdirectories:
- `examples/markdown`
- `examples/hyperscript`
- etc

And for example in `examples/markdown` directory all related files:
- `build.sh` that has `node index.js` or similar commands, that builds static website files. That build.sh should be executeable with `chmod +x build.sh`
- all other files that are required to build website

This would make figuring out usage easier.

**Comment by chr15m** [comment]
Good idea, will add an example project with all build Makefile etc.

**Comment by chr15m** [comment]
@xet7 just a quick note to let you know I created [create-motionless-site](https://github.com/chr15m/create-motionless-site) to help people bootstrap a static site with motionless like this:

```
npm i motionless-site MYSITE
cd MYSITE
make watch
```
